# Generated by Django 2.2.25 on 2023-06-29 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginVersionDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateField(default=django.utils.timezone.now)),
                ('download_count', models.IntegerField(default=0)),
                ('plugin_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.PluginVersion')),
            ],
            options={
                'unique_together': {('plugin_version', 'download_date')},
            },
        ),
    ]
