# Generated by Django 2.2.24 on 2021-09-24 02:10

from django.db import migrations, models

def default_slug(apps, schema_editor):
    Plugin = apps.get_model('plugins', 'Plugin')
    old_data = Plugin.objects.all()
    for data in old_data:
        data.slug = data.package_name
        data.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='plugin',
                    name='slug',
                    field=models.CharField(default='', max_length=400, verbose_name='Slug'),
                    preserve_default=False,
                ),
                migrations.RunPython(default_slug),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='plugin',
                    name='slug',
                    field=models.CharField(max_length=400, unique=True, verbose_name='Slug')
                )
            ],
        )
    ]
