# Generated by Django 2.2.25 on 2023-05-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginVersionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('comment', models.TextField(help_text='A review comment. Please write your review.', max_length=1000, verbose_name='Comment')),
                ('reviewer', models.ForeignKey(help_text='The user who reviewed this plugin.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='plugins.PluginVersion')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
