# Generated by Django 2.2.25 on 2023-03-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='package_name',
            field=models.CharField(help_text="This is the plugin's internal name, equals to the main folder name. Must start with an ASCII letter and can contain only ASCII letters, digits and the - and _ signs.", max_length=256, unique=True, verbose_name='Package Name'),
        ),
        migrations.CreateModel(
            name='PluginLegacyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('package_name', models.CharField(blank=True, editable=False, help_text="This is the plugin's internal name, equals to the main folder name", max_length=256, null=True, verbose_name='Package Name')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.Plugin')),
            ],
        ),
    ]
