# Generated by Django 2.2.25 on 2023-12-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_plugins_feedback'),
        ('plugins', '0003_plugin_allow_update_name'),
    ]

    operations = [
    ]
