# Generated by Django 3.2.11 on 2023-11-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_plugins_feedback'),
        ('plugins', '0003_plugin_allow_update_name'),
    ]

    operations = [
    ]
