# Generated by Django 2.2.25 on 2023-12-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_merge_20231122_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginDownloadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3)),
                ('downloaded_on', models.DateTimeField(auto_now_add=True)),
                ('plugin_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plugins.PluginVersion')),
            ],
        ),
    ]
