# Generated by Django 2.2.25 on 2023-11-29 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_maintainer(apps, schema_editor):
    Plugin = apps.get_model('plugins', 'Plugin')

    # Set the maintainer as the plugin creator by default
    for obj in Plugin.objects.all():
        obj.maintainer = obj.created_by 
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0004_merge_20231122_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugins_maintainer', to=settings.AUTH_USER_MODEL, verbose_name='Maintainer'),
        ),
        migrations.RunPython(populate_maintainer),
    ]
