# Generated by Django 2.2.25 on 2023-12-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_merge_20231122_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginversiondownload',
            name='country_code',
            field=models.CharField(default='N/D', max_length=3),
        ),
        migrations.AddField(
            model_name='pluginversiondownload',
            name='country_name',
            field=models.CharField(default='N/D', max_length=100),
        ),
    ]
