# Generated by Django 2.2.25 on 2024-01-09 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_auto_20231218_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginversion',
            name='is_from_token',
            field=models.BooleanField(default=False, verbose_name='Is uploaded using token'),
        ),
        migrations.AddField(
            model_name='pluginversion',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plugins.PluginOutstandingToken', verbose_name='Token used'),
        ),
        migrations.AlterField(
            model_name='pluginversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
