# Generated by Django 2.2.25 on 2024-02-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_auto_20240109_0428'),
        ('plugins', '0006_plugin_display_created_by'),
    ]

    operations = [
    ]
