# Generated by Django 4.2.11 on 2024-03-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_merge_20231123_0018'),
        ('plugins', '0008_merge_20240206_0448'),
    ]

    operations = [
    ]
