# Generated by Django 2.2.25 on 2024-04-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_merge_20240418_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginversion',
            name='max_qt_version',
            field=models.IntegerField(default=5, verbose_name='Maximum Qt version'),
        ),
        migrations.AddField(
            model_name='pluginversion',
            name='min_qt_version',
            field=models.IntegerField(default=5, verbose_name='Minimum Qt version'),
        ),
    ]
