# Generated by Django 4.2.13 on 2024-05-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_auto_20231214_2317'),
        ('plugins', '0009_merge_20240321_0207'),
    ]

    operations = [
    ]
