# Generated by Django 4.2.17 on 2025-01-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_pluginversionfeedback_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='server',
            field=models.BooleanField(db_index=True, default=False, help_text='A server plugin is a plugin which can run on QGIS Server, by having a entrypoint <code>serverClassFactory</code>, see the <a href="https://docs.qgis.org/latest/en/docs/pyqgis_developer_cookbook/server.html#init-py" target="_blank">documentation</a>.', verbose_name='Server'),
        ),
    ]
