import { test, expect } from '@playwright/test';

let url = '/';

test.use({
  storageState: 'auth.json'
});

test('test', async ({ page }) => {
  await page.goto(url);
  await expect(page.locator('h2')).toContainText('QGIS plugins web portal');
  await expect(page.getByRole('link', { name: 'Plugins', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Plugins', exact: true }).click();
  await expect(page.locator('#maincolumn')).toContainText('QGIS Python Plugins Repository');
  await expect(page.getByRole('link', { name: ' Upload a plugin' })).toBeVisible();
  await expect(page.locator('#collapse-related-plugins')).toContainText('Plugins');
  await expect(page.getByText('Featured')).toBeVisible();
  await expect(page.getByRole('link', { name: 'All' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Stable' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'New Plugins' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Updated Plugins' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Experimental' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Popular' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Most voted' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Top downloads' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Most rated' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QGIS Server plugins' })).toBeVisible();
  await expect(page.getByRole('button', { name: ' Plugin Tags ' })).toBeVisible();
  await page.getByRole('button', { name: ' Plugin Tags ' }).click();
  await expect(page.locator('#tagcloudModal').getByText('Plugin Tags')).toBeVisible();
  await page.locator('#tagcloudModal').getByText('×').click();
  await expect(page.getByRole('heading', { name: 'All plugins' })).toBeVisible();
  await expect(page.locator('#list_commands')).toContainText('2041 records found');
  await expect(page.getByRole('cell', { name: 'Name' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Featured' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Downloads' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Author' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Latest Plugin Version' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Created on' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Stars (votes)' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Stable' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Exp.' })).toBeVisible();
  await expect(page.locator('#pmain2176').getByRole('cell', { name: 'Plugin icon' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '3D City Builder' })).toBeVisible();
  await expect(page.locator('#pmain2176').getByRole('cell', { name: '—' }).first()).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Arthur Ruf Hosang da Costa' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Jul 6,' })).toBeVisible();
  await expect(page.getByRole('cell', { name: 'Oct 7, 2020' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '(65)' })).toBeVisible();
  await expect(page.locator('#pmain2176').getByRole('cell', { name: '—' }).nth(1)).toBeVisible();
  await expect(page.locator('#pmain2176').getByRole('cell', { name: '0.3' })).toBeVisible();
  await page.getByRole('link', { name: '3D City Builder' }).click();
  await expect(page.locator('#maincolumn')).toContainText('QGIS Python Plugins Repository');
  await expect(page.getByRole('heading', { name: '3D City Builder Plugin icon' })).toBeVisible();
  await expect(page.getByRole('link', { name: ' Download latest' })).toBeVisible();
  await expect(page.getByRole('img', { name: 'Plugin icon' })).toBeVisible();
  await expect(page.locator('#maincolumn')).toContainText('Plugin ID: 2176');
  //await expect(page.getByRole('button', { name: 'Copy to clipboard ' })).toBeVisible();
  await expect(page.getByRole('blockquote')).toContainText('Generate 3D models of urban areas using DEM.');
  await expect(page.getByRole('link', { name: 'About', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Details' }).click();
  await expect(page.getByText('Author')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Arthur Ruf Hosang da Costa' })).toBeVisible();
  await page.getByRole('link', { name: 'Versions' }).click();
  await expect(page.getByRole('cell', { name: 'Version', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '0.3' })).toBeVisible();
  await expect(page.getByText('Jul 6, 2021, 01:17 PM GMT+')).toBeVisible();
  await expect(page.getByRole('link', { name: '0.2' })).toBeVisible();
  await expect(page.getByText('Oct 7, 2020, 10:35 PM GMT+')).toBeVisible();
  await expect(page.locator('section').filter({ hasText: 'Sustaining Members' })).toBeVisible();
  await expect(page.locator('header')).toContainText('Sustaining Members');
  //await expect(page.getByRole('link', { name: 'Sustaining member logos' })).toBeVisible();
  await page.getByText('Featured').click();
  await expect(page.locator('#list_commands')).toContainText('22 records found');
  await expect(page.getByRole('link', { name: 'Processing R Provider' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Data Plotly' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Shape Tools' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Split Features On Steroids' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Plugin Builder' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QGIS Resource Sharing' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Lat Lon Tools' })).toBeVisible();
  await page.getByRole('link', { name: 'All', exact: true }).click();
  await expect(page.locator('#list_commands')).toContainText('2041 records found');
  await expect(page.getByRole('link', { name: '3D City Builder' })).toBeVisible();
  await expect(page.getByRole('link', { name: '3DCityDB Tools' })).toBeVisible();
  await page.getByRole('link', { name: 'Stable' }).click();
  await expect(page.locator('#list_commands')).toContainText('1534 records found');
  await expect(page.getByRole('link', { name: '3DCityDB Tools' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'AGIS' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'AGT - Archaeological' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'ALS Downloader' })).toBeVisible();
  await page.getByRole('link', { name: 'New Plugins' }).click();
  await expect(page.locator('#list_commands')).toContainText('18 records found');
  await expect(page.getByRole('link', { name: 'Environmental Data Retrival' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QTalsim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'RubberSheetingEtc' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'OpenLog' })).toBeVisible();
  await page.getByRole('link', { name: 'Updated Plugins' }).click();
  await expect(page.locator('#list_commands')).toContainText('98 records found');
  await expect(page.getByRole('link', { name: 'Speckle', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QGIS Cloud Plugin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'PgMetadata' })).toBeVisible();
  await page.getByRole('link', { name: 'Experimental' }).click();
  await expect(page.locator('#list_commands')).toContainText('951 records found');
  await expect(page.getByRole('link', { name: '3D City Builder' })).toBeVisible();
  await expect(page.getByRole('link', { name: '3DCityDB Tools' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'A-Maps' })).toBeVisible();
  await page.getByRole('link', { name: 'Popular' }).click();
  await expect(page.locator('#list_commands')).toContainText('1960 records found');
  await expect(page.getByRole('link', { name: 'QuickMapServices' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'OpenLayers Plugin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Semi-Automatic Classification' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QuickOSM' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Popular plugins' })).toBeVisible();
  await page.getByRole('link', { name: 'Most voted' }).click();
  await expect(page.locator('#maincolumn')).toContainText('Most voted plugins');
  await expect(page.getByRole('link', { name: 'OpenLayers Plugin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QuickMapServices' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Semi-Automatic Classification' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'qgis2web' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'qgis2web' })).toBeVisible();
  await page.getByRole('link', { name: 'Top downloads' }).click();
  await expect(page.locator('#maincolumn')).toContainText('Most downloaded plugins');
  await expect(page.locator('#list_commands')).toContainText('1960 records found');
  await expect(page.getByRole('link', { name: 'QuickMapServices' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'OpenLayers Plugin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Semi-Automatic Classification' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'QuickOSM' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'mmqgis' })).toBeVisible();
  await page.getByRole('link', { name: 'Most rated' }).click();
  await expect(page.locator('#maincolumn')).toContainText('Most rated plugins');
  await expect(page.locator('#list_commands')).toContainText('1960 records found');
  await expect(page.getByRole('link', { name: 'D4C Plugin' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Terraform' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Otoklim' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cloudant Client' })).toBeVisible();
  await page.getByRole('link', { name: 'QGIS Server plugins' }).click();
  await page.getByRole('heading', { name: 'QGIS Server plugins' }).click();
  await expect(page.locator('#list_commands')).toContainText('11 records found');
  await expect(page.getByRole('link', { name: 'Data Plotly' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'GeoJson Renderer' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'HelloServer' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Lizmap server' })).toBeVisible();
  await page.getByRole('link', { name: 'Click to toggle descriptions.' }).click();
  await page.getByRole('link', { name: 'Click to toggle descriptions.' }).click();
});
