# Generated by Django 2.2 on 2020-11-08 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("styles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="style",
            managers=[],
        ),
        migrations.CreateModel(
            name="StyleReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The review date. Automatically added on style review.",
                        verbose_name="Reviewed on",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="The user who reviewed this style.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styles_reviewed_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed by",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        help_text="The type of this style, this will automatically be read from the XML file.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="styles.Style",
                        verbose_name="Style",
                    ),
                ),
            ],
        ),
    ]
