# Generated by Django 2.2.13 on 2020-12-15 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("styles", "0007_auto_20201109_0112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="style",
            name="approved",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set to True if you wish to approve this resource.",
                verbose_name="Approved",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="creator",
            field=models.ForeignKey(
                help_text="The user who uploaded this resource.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="download_count",
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text="The number of times this resource has been downloaded. This is updated automatically.",
                verbose_name="Downloads",
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="require_action",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set to True if you require creator to update the resource.",
                verbose_name="Requires Action",
            ),
        ),
        migrations.AlterField(
            model_name="stylereview",
            name="review_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The review date. Automatically added on review resource.",
                verbose_name="Reviewed on",
            ),
        ),
        migrations.AlterField(
            model_name="stylereview",
            name="reviewer",
            field=models.ForeignKey(
                help_text="The user who reviewed this GeoPackage.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
    ]
