# Generated by Django 2.2.13 on 2021-01-21 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("styles", "0008_auto_20201215_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylereview",
            name="reviewer",
            field=models.ForeignKey(
                help_text="The user who reviewed this GeoPackage.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="styles_stylereview_related",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
    ]
