# Generated by Django 2.2.13 on 2021-02-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_Review_model_and_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='The user who reviewed this %(app_label)s.', on_delete=django.db.models.deletion.CASCADE, related_name='models_review_related', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
    ]
