# Generated by Django 2.2.13 on 2021-02-10 19:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0005_populate_uuid_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
