# Generated by Django 4.2.16 on 2024-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_model_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='dependencies',
            field=models.TextField(blank=True, help_text='Comma-separated list for the plugin the model needs', null=True, verbose_name='Plugin dependencies'),
        ),
    ]
