#!/bin/bash

# This script will get (via wget) the (uncached!) version of the plugins.xml
# and save it in /home/plugins/cached_xmls/plugins as plugins_x.x.xml
# It serves as a cache, and will be served by the plugins django app.
#
# This script is to be run via crontab every 10 minutes:
#
# */10 * * * * cd /home/plugins/QGIS-Django/scripts;./get_plugins_xml;
#
# given that currently in the plugins container the Django app is in
# /home/plugins/QGIS-Django

DEST_DIR="/home/plugins/cached_xmls/plugins"
BASE_URL="http://plugins.qgis.org/plugins/plugins_new.xml"

for VERSION in 2.18 2.99 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 3.10 3.11 3.12 3.13; do
    if [[ -f $DEST_DIR/plugins_${VERSION}.xml.temp ]]; then
        rm $DEST_DIR/plugins_${VERSION}.xml.temp
    fi
    wget -q -O $DEST_DIR/plugins_${VERSION}.xml.temp "$BASE_URL?qgis=${VERSION}"
    if [[ -s $DEST_DIR/plugins_${VERSION}.xml.temp ]]; then
        # we want all download url's to be https, search/replace in file
        sed -i'' 's,<download_url>http:,<download_url>https:,' $DEST_DIR/plugins_${VERSION}.xml.temp
        mv $DEST_DIR/plugins_${VERSION}.xml.temp $DEST_DIR/plugins_${VERSION}.xml
        sleep 5s
    fi
done;
