# Generated by Django 2.2.13 on 2020-12-15 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geopackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopackage',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if you wish to approve this resource.', verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='creator',
            field=models.ForeignKey(help_text='The user who uploaded this resource.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='description',
            field=models.TextField(help_text='A description of this resource.', max_length=5000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='download_count',
            field=models.IntegerField(default=0, editable=False, help_text='The number of times this resource has been downloaded. This is updated automatically.', verbose_name='Downloads'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='gpkg_file',
            field=models.FileField(help_text='A GeoPackage file. The filesize must less than 1MB ', upload_to='geopackages/%Y', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gpkg', 'zip'])], verbose_name='GeoPackage file'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='name',
            field=models.CharField(help_text='A unique name for this resource', max_length=256, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='require_action',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True if you require creator to update the resource.', verbose_name='Requires Action'),
        ),
        migrations.AlterField(
            model_name='geopackage',
            name='thumbnail_image',
            field=models.ImageField(help_text='Please upload an image that demonstrate this resource.', upload_to='geopackages/%Y', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='geopackagereview',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The review date. Automatically added on review resource.', verbose_name='Reviewed on'),
        ),
        migrations.AlterField(
            model_name='geopackagereview',
            name='reviewer',
            field=models.ForeignKey(help_text='The user who reviewed this GeoPackage.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
    ]
