# Generated by Django 2.2.13 on 2021-02-03 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geopackages", "0004_auto_20210121_0227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="The user who reviewed this %(app_label)s.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geopackages_review_related",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
    ]
