# Generated by Django 2.2.13 on 2021-02-10 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geopackages', '0005_auto_20210203_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopackage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
